services:
  - type: web
    name: sulongedukasyon
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sulongedukasyon-db
          property: connectionString

databases:
  - name: sulongedukasyon-db
    databaseName: sulongedukasyon_production
    plan: starter